### ISSUE TITLE
add the quais.js lib to dependencies and connect to quai network

### ISSUE THREAD

**Issue by ssallam** [dominant-strategies/quaipay#15]
- add quais.js lib to the dependencies
- initialize a new connection using quai testnet
- make a call to the quai node rpc to fetch a block successfully

**Comment by ssallam** [comment]
needs a test of getting a block from the node.

**Comment by obasilakis** [comment]
I was able to get a block from the node manually. Moving to done as my next task (sending transactions) will include connecting to the network.
