### ISSUE TITLE
build the Scan to pay page (Send flow - scan QR)

### ISSUE THREAD

**Issue by ssallam** [dominant-strategies/quaipay#28]
The design is here: 
https://www.figma.com/file/OsfoenLSvHh5r8Nc1E7i1g/QuaiPay-Design?type=design&node-id=334-7414&t=HPYvuhMNU26ITPKb-0

Details:
- Requires camera access to scan the QR code 
- there is two variations here which determine what is displayed in the next screen (the Send Amount screen): 
  1. Scan static QR code -- has only the receiver address information, navigates to this screen (https://github.com/dominant-strategies/quaipay/issues/47)
    https://www.figma.com/file/OsfoenLSvHh5r8Nc1E7i1g/QuaiPay-Design?type=design&node-id=334-7064&t=HPYvuhMNU26ITPKb-0
  3. Scan dynamic QR code -- has the receiver address, name and preset amount, navigates to this screen (https://github.com/dominant-strategies/quaipay/issues/49)
    https://www.figma.com/file/OsfoenLSvHh5r8Nc1E7i1g/QuaiPay-Design?type=design&node-id=334-7594&t=HPYvuhMNU26ITPKb-0

Image from Figma design for quick reference (both light and dark modes):
![image](https://github.com/dominant-strategies/quaipay/assets/36411297/48498e12-c6fa-40cd-a6fd-1fb71dcdba24)
![image](https://github.com/dominant-strategies/quaipay/assets/36411297/95e27287-a4c8-4814-a932-bc052239aa00)

**Comment by alanorwick** [comment]
![Image](https://github.com/dominant-strategies/quaipay/assets/14866363/8444dbe6-3e0e-40d6-bbbd-bdf0ba08b7d3)

**Comment by alanorwick** [comment]
Black background between dark/light mode on QR scan should mimic the overlay of the full camera like the above example.
