### ISSUE TITLE
Build the Request page (Request Flow 2/3)

### ISSUE THREAD

**Issue by ssallam** [dominant-strategies/quaipay#44]
The design is here:
https://www.figma.com/file/OsfoenLSvHh5r8Nc1E7i1g/QuaiPay-Design?type=design&node-id=334-8192&t=YczZt5UEcN0yjLgz-0

Notes:
- Request flow step 2

Details:
- Display number keypad 
- Allows user to type in an amount for the request
- Pressing the continue button navigates to a variation of the HomeScreen with QR code that has the amount already set as in this figma design (https://github.com/dominant-strategies/quaipay/issues/45)
  https://www.figma.com/file/OsfoenLSvHh5r8Nc1E7i1g/QuaiPay-Design?type=design&node-id=334-8870&t=YczZt5UEcN0yjLgz-0

Image from Figma design for quick reference (both light and dark modes):
![Image](https://github.com/dominant-strategies/quaipay/assets/36411297/32c6cde5-45e0-4026-be8b-9ad5aef0e747)  ![Image](https://github.com/dominant-strategies/quaipay/assets/36411297/76f3a089-3eec-4b1b-8f0b-3fa406b32cd5)

**Comment by juanmanso** [comment]
Hey team, one question here regarding theming.

From what we can see on the description of this issue, the keyboard is using a darker tone on the light theme and a lighter one on the dark theme.

This seems inconsistent with the overall design of the flow, where the background color of the Home matches the background of the keyboard as shown on the comparison below,

| _Light theme_ | <img width="790" alt="image" src="https://github.com/dominant-strategies/quaipay/assets/21087992/067a688e-4192-4d4e-8af6-5c808cd2fc60"> |
| :---: | :---: |
| _Dark theme_ | <img width="805" alt="image" src="https://github.com/dominant-strategies/quaipay/assets/21087992/b97709d3-368e-487d-88ee-968b8e63b5be"> |

**How should we proceed?**
